const ESTADOS_CON_CONTROL_HORAS = new Set([
  'EN_EJECUCION',
  'INFORME_FINAL_PRESENTADO',
  'INFORME_EN_REVISION',
  'INFORME_APROBADO',
  'EVALUACION_PENDIENTE',
  'EVALUACION_EMPRESA_PENDIENTE',
  'EVALUACION_COMPLETA',
  'DICTAMEN_EMITIDO',
  'EVALUADO',
  'CERRADO',
  'SUSPENDIDO',
]);

export const tieneControlHoras = (estado) => ESTADOS_CON_CONTROL_HORAS.has(estado);
