// Estados exactos definidos en el backend (EstadoExpediente.java)
export const ESTADOS_EXPEDIENTE = {
  SOLICITADO: 'SOLICITADO',
  EMPRESA_SEDE_ASIGNADA: 'EMPRESA_SEDE_ASIGNADA',
  VALIDADO_SECRETARIA: 'VALIDADO_SECRETARIA',
  CARTA_PRESENTACION_EMITIDA: 'CARTA_PRESENTACION_EMITIDA',
  CARTA_ACEPTACION_PRESENTADA: 'CARTA_ACEPTACION_PRESENTADA',
  ASESOR_ASIGNADO: 'ASESOR_ASIGNADO',
  COMITE_ASIGNADO: 'COMITE_ASIGNADO',
  PLAN_PRESENTADO: 'PLAN_PRESENTADO',
  PLAN_EN_REVISION: 'PLAN_EN_REVISION',
  PLAN_EN_REVISION_COMITE: 'PLAN_EN_REVISION_COMITE',
  PLAN_APROBADO: 'PLAN_APROBADO',
  PLAN_OBSERVADO: 'PLAN_OBSERVADO',
  EN_EJECUCION: 'EN_EJECUCION',
  INFORME_PARCIAL_1_PRESENTADO: 'INFORME_PARCIAL_1_PRESENTADO',
  INFORME_PARCIAL_2_PRESENTADO: 'INFORME_PARCIAL_2_PRESENTADO',
  INFORME_FINAL_PRESENTADO: 'INFORME_FINAL_PRESENTADO',
  INFORME_EN_REVISION: 'INFORME_EN_REVISION',
  INFORME_APROBADO: 'INFORME_APROBADO',
  EVALUACION_EMPRESA_PENDIENTE: 'EVALUACION_EMPRESA_PENDIENTE',
  EVALUACION_COMPLETA: 'EVALUACION_COMPLETA',
  EVALUADO: 'EVALUADO',
  EXAMEN_APLAZADOS_HABILITADO: 'EXAMEN_APLAZADOS_HABILITADO',
  EXAMEN_APLAZADOS_RENDIDO: 'EXAMEN_APLAZADOS_RENDIDO',
  DICTAMEN_EMITIDO: 'DICTAMEN_EMITIDO',
  CERRADO: 'CERRADO',
  SUBSANADO: 'SUBSANADO',
  OBSERVADO: 'OBSERVADO',
  SUSPENDIDO: 'SUSPENDIDO',
} as const;

// Estados de revisión documental (documentos adjuntos)
export const ESTADOS_REVISION_DOCUMENTAL = {
  PENDIENTE: 'PENDIENTE',
  EN_REVISION: 'EN_REVISION',
  APROBADO: 'APROBADO',
  OBSERVADO: 'OBSERVADO',
  RECHAZADO: 'RECHAZADO',
  ARCHIVADO: 'ARCHIVADO',
} as const;

// Estados de plan general
export const ESTADOS_PLAN_GENERAL = {
  BORRADOR: 'BORRADOR',
  PRESENTADO: 'PRESENTADO',
  EN_REVISION: 'EN_REVISION',
  OBSERVADO: 'OBSERVADO',
  APROBADO: 'APROBADO',
  RECHAZADO: 'RECHAZADO',
} as const;

// Estados de informe
export const ESTADOS_INFORME = {
  BORRADOR: 'BORRADOR',
  PRESENTADO: 'PRESENTADO',
  EN_REVISION: 'EN_REVISION',
  OBSERVADO: 'OBSERVADO',
  APROBADO: 'APROBADO',
} as const;

export const ESTADOS_CON_PLAN_EN_REVISION = [
  ESTADOS_EXPEDIENTE.PLAN_PRESENTADO,
  ESTADOS_EXPEDIENTE.PLAN_EN_REVISION,
  ESTADOS_EXPEDIENTE.PLAN_EN_REVISION_COMITE,
  ESTADOS_EXPEDIENTE.PLAN_OBSERVADO,
  ESTADOS_EXPEDIENTE.SUBSANADO,
];

export const ESTADOS_INFORME_PARCIAL_PRESENTADO = [
  ESTADOS_EXPEDIENTE.INFORME_PARCIAL_1_PRESENTADO,
  ESTADOS_EXPEDIENTE.INFORME_PARCIAL_2_PRESENTADO,
];

export const ESTADOS_EVALUABLES = [
  ESTADOS_EXPEDIENTE.INFORME_APROBADO,
  ESTADOS_EXPEDIENTE.EVALUACION_COMPLETA,
  ESTADOS_EXPEDIENTE.EVALUADO,
  ESTADOS_EXPEDIENTE.DICTAMEN_EMITIDO,
];

// Estados en los que el informe (parcial o final) ya fue presentado y requiere evaluación/seguimiento
export const ESTADOS_PARA_EVALUAR = [
  ESTADOS_EXPEDIENTE.INFORME_PARCIAL_1_PRESENTADO,
  ESTADOS_EXPEDIENTE.INFORME_PARCIAL_2_PRESENTADO,
  ESTADOS_EXPEDIENTE.INFORME_FINAL_PRESENTADO,
];

// Estados habilitados para emitir el dictamen final
export const ESTADOS_PARA_DICTAMEN = [
  ESTADOS_EXPEDIENTE.INFORME_APROBADO,
  ESTADOS_EXPEDIENTE.EVALUACION_COMPLETA,
  ESTADOS_EXPEDIENTE.EVALUADO,
];

// Estados que indican que el expediente ya culminó su ciclo activo
export const ESTADOS_FINALIZADOS = [
  ESTADOS_EXPEDIENTE.EVALUADO,
  ESTADOS_EXPEDIENTE.CERRADO,
];
